# Generated by Django 6.0.4 on 2026-04-08 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Preenchimento')),
                ('diabetico', models.BooleanField(default=False, verbose_name='Diabético?')),
                ('hipertenso', models.BooleanField(default=False, verbose_name='Hipertenso?')),
                ('problema_circulacao', models.BooleanField(default=False, verbose_name='Problemas de Circulação?')),
                ('problema_cicatrizacao', models.BooleanField(default=False, verbose_name='Problemas de Cicatrização?')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias (Quais?)')),
                ('cirurgias_anteriores', models.TextField(blank=True, null=True, verbose_name='Cirurgias Anteriores')),
                ('medicamentos_continuos', models.TextField(blank=True, null=True, verbose_name='Uso de Medicamentos Mencionados')),
                ('pratica_esporte', models.BooleanField(default=False, verbose_name='Pratica Esportes?')),
                ('tipo_calcado_diario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipos de Calçados mais usados no Dia a Dia')),
                ('tipo_pe', models.CharField(choices=[('N', 'Normal'), ('P', 'Plano (Chato)'), ('C', 'Cavo')], default='N', max_length=1, verbose_name='Tipo de Pé')),
                ('tipo_pisada', models.CharField(choices=[('N', 'Neutra'), ('P', 'Pronada (Para dentro)'), ('S', 'Supinada (Para fora)')], default='N', max_length=1, verbose_name='Tipo de Pisada')),
                ('alteracoes_unhas', models.TextField(blank=True, null=True, verbose_name='Alterações nas Unhas (Onicocriptose, etc)')),
                ('queixa_principal', models.TextField(verbose_name='Queixa Principal / Motivo da Consulta')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Ficha de Anamnese',
                'verbose_name_plural': 'Fichas de Anamnese',
            },
        ),
    ]
