# Generated by Django 6.0.4 on 2026-04-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fichaanamnese'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Material/Insumo')),
                ('unidade_medida', models.CharField(help_text='Ex: Unidade, Caixa, Pacote, ML', max_length=50, verbose_name='Unidade de Medida')),
                ('quantidade_atual', models.IntegerField(default=0, help_text='Atualizado automaticamente pelas movimentações', verbose_name='Quantidade Atual')),
                ('estoque_minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo Ideal')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Estoque de Materiais',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Compra, Reposição, Descarte, Uso no Atendimento X', max_length=255, null=True, verbose_name='Motivo (Opcional)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.material')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Histórico de Movimentações',
            },
        ),
    ]
